<?php
// Flo Faction Insurance - Contact Form Processor

// Set error reporting for development
error_reporting(E_ALL);
ini_set('display_errors', 1);

// Start session for CSRF token
session_start();

// Allow CORS for form submission
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');

// Handle preflight OPTIONS request
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(200);
    exit();
}

// Only process POST requests
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['error' => 'Method not allowed']);
    exit();
}

// Get JSON input
$input = file_get_contents('php://input');
$data = json_decode($input, true);

if (!$data) {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid JSON data']);
    exit();
}

// CSRF token validation
$csrf_token_from_client = $data['csrf_token'] ?? '';
if (empty($_SESSION['csrf_token']) || !hash_equals($_SESSION['csrf_token'], $csrf_token_from_client)) {
    http_response_code(403);
    echo json_encode(['error' => 'Invalid CSRF token']);
    exit();
}

// Extract form data
$formData = $data['formData'] ?? [];

// Validate required fields
$requiredFields = ['contactFirstName', 'contactLastName', 'contactEmail', 'contactSubject', 'contactMessage'];
foreach ($requiredFields as $field) {
    if (empty($formData[$field])) {
        http_response_code(400);
        echo json_encode(['error' => "Missing required field: $field"]);
        exit();
    }
}

// Sanitize data
$firstName = htmlspecialchars($formData['contactFirstName']);
$lastName = htmlspecialchars($formData['contactLastName']);
$email = filter_var($formData['contactEmail'], FILTER_VALIDATE_EMAIL);
if (!$email) {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid email address']);
    exit();
}
$subject = htmlspecialchars($formData['contactSubject']);
$message = htmlspecialchars($formData['contactMessage']);
$phone = htmlspecialchars($formData['contactPhone'] ?? 'Not provided');

$clientName = "$firstName $lastName";

// Your email address (primary recipient)
$yourEmail = 'flofaction.insurance@gmail.com'; // Or a dedicated contact email

// Prepare email content
$emailSubject = "🌐 New Website Contact Form Submission: $subject";

$body = "
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .header { background: #28a745; color: white; padding: 20px; text-align: center; }
        .content { padding: 20px; }
        .section { margin: 20px 0; padding: 15px; border-left: 4px solid #28a745; background: #f8f9fa; }
    </style>
</head>
<body>
    <div class='header'>
        <h1>🌐 NEW CONTACT FORM SUBMISSION</h1>
        <p>From FloFaction Website</p>
    </div>
    
    <div class='content'>
        <div class='section'>
            <h2>👤 SENDER INFORMATION</h2>
            <p><strong>Name:</strong> $clientName</p>
            <p><strong>Email:</strong> $email</p>
            <p><strong>Phone:</strong> $phone</p>
        </div>
        
        <div class='section'>
            <h2>✉️ MESSAGE DETAILS</h2>
            <p><strong>Subject:</strong> $subject</p>
            <p><strong>Message:</strong><br>$message</p>
        </div>
        
        <p style='margin-top: 30px; text-align: center; color: #666;'>
            This email was automatically generated by the Flo Faction website contact form.
        </p>
    </div>
</body>
</html>
";

// Email headers
$headers = array(
    'MIME-Version: 1.0',
    'Content-type: text/html; charset=UTF-8',
    'From: Flo Faction Website <noreply@flofaction.com>',
    'Reply-To: ' . $email,
    'X-Mailer: PHP/' . phpversion()
);

// Send email
$mailSent = mail($yourEmail, $emailSubject, $body, implode("\r\n", $headers));

// Log email status
if (!$mailSent) {
    error_log("Failed to send contact form email to $yourEmail");
}

// Return success response
$response = [
    'success' => true,
    'message' => 'Your message has been sent successfully!',
    'emailSent' => $mailSent,
    'timestamp' => date('Y-m-d H:i:s')
];

echo json_encode($response);

?>