<?php
// Flo Faction Insurance - Quote Form Processor

// Set error reporting for development
error_reporting(E_ALL);
ini_set('display_errors', 1);

// Start session for CSRF token
session_start();

// Allow CORS for form submission
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');

// Handle preflight OPTIONS request
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(200);
    exit();
}

// Only process POST requests
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['error' => 'Method not allowed']);
    exit();
}

// Get JSON input
$input = file_get_contents('php://input');
$data = json_decode($input, true);

if (!$data) {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid JSON data']);
    exit();
}

// CSRF token validation
// This assumes the CSRF token is sent in the JSON body as 'csrf_token'
// If it's sent as a form field, you'd access $_POST['csrf_token']
$csrf_token_from_client = $data['csrf_token'] ?? '';
if (empty($_SESSION['csrf_token']) || !hash_equals($_SESSION['csrf_token'], $csrf_token_from_client)) {
    http_response_code(403);
    echo json_encode(['error' => 'Invalid CSRF token']);
    exit();
}

// Extract form data
$formData = $data['formData'] ?? [];

// Validate required fields
$requiredFields = ['firstName', 'lastName', 'email', 'phone', 'insuranceType'];
foreach ($requiredFields as $field) {
    if (empty($formData[$field])) {
        http_response_code(400);
        echo json_encode(['error' => "Missing required field: $field"]);
        exit();
    }
}

// Sanitize data
$firstName = htmlspecialchars($formData['firstName']);
$lastName = htmlspecialchars($formData['lastName']);
$email = filter_var($formData['email'], FILTER_VALIDATE_EMAIL);
if (!$email) {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid email address']);
    exit();
}
$phone = htmlspecialchars($formData['phone']);
$insuranceType = htmlspecialchars($formData['insuranceType']);
$coverageAmount = htmlspecialchars($formData['coverageAmount'] ?? 'Not specified');
$additionalInfo = htmlspecialchars($formData['additionalInfo'] ?? 'None provided');

$clientName = "$firstName $lastName";

// Your email address (primary recipient)
$yourEmail = 'flofaction.insurance@gmail.com';

// Prepare email content
$subject = "⚡ NEW QUOTE REQUEST: $clientName ($insuranceType)";

$body = "
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .header { background: #007bff; color: white; padding: 20px; text-align: center; }
        .content { padding: 20px; }
        .section { margin: 20px 0; padding: 15px; border-left: 4px solid #007bff; background: #f8f9fa; }
        .highlight { background: #e8f5e8; padding: 10px; border-radius: 5px; margin: 10px 0; }
    </style>
</head>
<body>
    <div class='header'>
        <h1>⚡ NEW INSURANCE QUOTE REQUEST</h1>
        <p>Flo Faction Insurance</p>
    </div>
    
    <div class='content'>
        <div class='section'>
            <h2>👤 CLIENT INFORMATION</h2>
            <p><strong>Name:</strong> $clientName</p>
            <p><strong>Email:</strong> $email</p>
            <p><strong>Phone:</strong> $phone</p>
        </div>
        
        <div class='section'>
            <h2>🛡️ QUOTE DETAILS</h2>
            <p><strong>Insurance Type:</strong> $insuranceType</p>
            <p><strong>Coverage Amount:</strong> $coverageAmount</p>
            <p><strong>Additional Info:</strong> $additionalInfo</p>
        </div>
        
        <div class='highlight'>
            <h3>🚀 NEXT STEPS:</h3>
            <ol>
                <li>Review client's request.</li>
                <li>Generate personalized quotes from carriers.</li>
                <li>Contact client to discuss options.</li>
            </ol>
        </div>
        
        <p style='margin-top: 30px; text-align: center; color: #666;'>
            This email was automatically generated by the Flo Faction Insurance quote request system.
        </p>
    </div>
</body>
</html>
";

// Email headers
$headers = array(
    'MIME-Version: 1.0',
    'Content-type: text/html; charset=UTF-8',
    'From: Flo Faction Insurance <noreply@flofaction.com>',
    'Reply-To: ' . $email,
    'X-Mailer: PHP/' . phpversion()
);

// Send email to you (primary)
$mailSent = mail($yourEmail, $subject, $body, implode("\r\n", $headers));

// Log email status
if (!$mailSent) {
    error_log("Failed to send quote request email to $yourEmail");
}

// Return success response
$response = [
    'success' => true,
    'message' => 'Quote request submitted successfully!',
    'emailSent' => $mailSent,
    'timestamp' => date('Y-m-d H:i:s')
];

echo json_encode($response);

?>